# Generated by Django 5.1.3 on 2024-11-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_order_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='accounts_orderitems',
        ),
    ]
