# Generated by Django 5.1.3 on 2024-11-29 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_mymodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyModel",
        ),
        migrations.AlterModelTable(
            name="orderitem",
            table=None,
        ),
    ]
