# Generated by Django 5.1.3 on 2024-12-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_orderdetails"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderdetails",
            name="order_date",
        ),
    ]
