# Generated by Django 5.1.3 on 2024-12-01 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_orderdetails_order_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderDetails",
        ),
    ]
