# Generated by Django 5.1.3 on 2024-12-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_orderdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.IntegerField()),
                ("customer_id", models.IntegerField()),
                ("customer_email", models.CharField(max_length=255)),
                ("full_address", models.CharField(max_length=255)),
                ("product_id", models.IntegerField()),
                ("product_name", models.CharField(max_length=255)),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
